### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Montenegrojds** [Cesar177/Trivia_Pirata#2]
![error si no pones numero](https://user-images.githubusercontent.com/11166234/190542973-6a8b0e06-2d68-40c6-9e7c-80eafefac379.PNG)

Hacer que no ingresas número no se detenga el programa por no ingresar un int, si no que te diga una advertencia o te quite el puntaje y pasar a la siguiente pregunta

**Comment by Cesar177** [comment]
Se solvento el punto observado, el participante al ingresar un valor diferente a un numero (int), saldra un mensaje de advertencia hasta que el participante ingrese el valor numero que este incluida en las alternativas.

![image](https://user-images.githubusercontent.com/71531985/190832924-9176c0ee-1c8b-4a83-86bb-cee717f058b3.png)
