### ISSUE TITLE
Preguntas

### ISSUE THREAD

**Issue by Montenegrojds** [Cesar177/Trivia_Pirata#3]
Agregar mas preguntas
![4](https://user-images.githubusercontent.com/11166234/190562785-5cfa0cfa-3a49-47e1-86be-3569e43499e5.PNG)

**Comment by Cesar177** [comment]
Se agregaron mas preguntas a la trivia.

![image](https://user-images.githubusercontent.com/71531985/190843865-d198f284-500c-4b37-a2ca-2d64dd8f38e7.png)
