### ISSUE TITLE
Color para diferenciar

### ISSUE THREAD

**Issue by Montenegrojds** [Cesar177/Trivia_Pirata#4]
![imagen](https://user-images.githubusercontent.com/11166234/190563077-a34ccd8f-1e52-42e5-8e2f-41ed9c209b36.png)
Otro color para el resultado

**Comment by Cesar177** [comment]
Se modifico la coloracion al resultado final de la trivia.

![image](https://user-images.githubusercontent.com/71531985/190839942-657abfdb-3608-4743-a7e1-5520d42dd14d.png)
